# -*- coding: utf-8 -*-
"""inadimplência

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrRucNBC5aHISp20J0aqtudNqOR5I5Jh
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from scipy import stats
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import os
import warnings
warnings.filterwarnings('ignore')

# ─── Configurações visuais ────────────────────────────────────────────────────
C0 = "#2ecc71"   # Adimplente
C1 = "#e74c3c"   # Inadimplente
BG = "#f8f9fa"
ACCENT = "#2c3e50"
OUT = "graficos_correlacao/"

plt.rcParams.update({
    'font.family': 'DejaVu Sans',
    'axes.facecolor': BG,
    'figure.facecolor': 'white',
    'axes.spines.top': False,
    'axes.spines.right': False,
})

os.makedirs(OUT, exist_ok=True)

"""from google.colab import files

---


uploaded = files.upload()
"""

# obs: para criar um token e ver seu nome de usuário acesse https://www.kaggle.com/settings
!pip install opendatasets

import opendatasets
opendatasets.download('https://www.kaggle.com/datasets/yasserh/loan-default-dataset')
df = pd.read_csv('loan-default-dataset/Loan_Default.csv')

df.isnull().sum()

cols = ['income', 'dtir1', 'loan_amount', 'Credit_Score', 'LTV']


stats = df[cols].describe().T


stats['variancia'] = df[cols].var()
stats['assimetria'] = df[cols].skew()
stats['curtose'] = df[cols].kurt()
stats['IQR'] = stats['75%'] - stats['25%']
print(stats)

import missingno as msno
msno.matrix(df[['income', 'dtir1', 'rate_of_interest', 'Upfront_charges']])

df_inadimplentes = df[df['Status'] == 1]

faltantes_por_linha = df_inadimplentes.isnull().sum(axis=1)

# linhas que têm MAIS de 5 dados faltantes
casos_criticos = faltantes_por_linha[faltantes_por_linha > 5]


total_inadimplentes = len(df_inadimplentes)
qtd_casos_criticos = len(casos_criticos)
percentual = (qtd_casos_criticos / total_inadimplentes) * 100

print(f"--- ANÁLISE DE INADIMPLÊNCIA VS. DADOS AUSENTES ---")
print(f"Total de casos de inadimplência no dataset: {total_inadimplentes}")
print(f"Casos de inadimplência com > 5 colunas faltantes: {qtd_casos_criticos}")
print(f"Isso representa {percentual:.2f}% de todos os inadimplentes.")

colunas_criticas = [
    'rate_of_interest', 'Interest_rate_spread', 'Upfront_charges',
    'property_value', 'LTV', 'dtir1', 'income'
]

print("DADOS AUSENTES (STATUS 1 / TOTAL NULOS)")

for col in colunas_criticas:

    df_nulos_coluna = df[df[col].isnull()]

    total_nulos = len(df_nulos_coluna)

    if total_nulos > 0:
        qtd_status_1 = df_nulos_coluna['Status'].sum()
        percentual = (qtd_status_1 / total_nulos) * 100

        print(f"Coluna: {col:22} | Nulos: {total_nulos:6} | Inadimplentes: {percentual:6.2f}%")

total_inadimplentes = (df['Status'] == 1).sum()


colunas_analise = ['rate_of_interest', 'Interest_rate_spread', 'Upfront_charges',
    'property_value', 'LTV', 'dtir1', 'income']

print(f"Total de casos de inadimplência (Status 1): {total_inadimplentes}\n")
print(f"{'Coluna':<20} | {'Nulos no Status 1':<18} | {'% do Total de Calotes'}")
print("-" * 65)

for col in colunas_analise:

    nulos_no_status_1 = df[df[col].isnull() & (df['Status'] == 1)].shape[0]

    porcentagem_do_calote = (nulos_no_status_1 / total_inadimplentes) * 100

    print(f"{col:<20} | {nulos_no_status_1:<18} | {porcentagem_do_calote:>18.2f}%")

nulos_combinados = df[df['rate_of_interest'].isnull() & df['income'].isnull()].shape[0]

print(f"Total de linhas onde Taxa e Renda são nulos: {nulos_combinados}")

nulos_combinados = df[df['rate_of_interest'].isnull() & df['dtir1'].isnull()].shape[0]

print(f"Total de linhas onde ambos Taxa e divida são nulos: {nulos_combinados}")

intersecoes = {
    'Renda (income)': df[df['rate_of_interest'].isnull() & df['income'].isnull()].shape[0],
    'DTI (dtir1)': df[df['rate_of_interest'].isnull() & df['dtir1'].isnull()].shape[0],
    'Valor Imóvel (property_value)': df[df['rate_of_interest'].isnull() & df['property_value'].isnull()].shape[0],
    'LTV': df[df['rate_of_interest'].isnull() & df['LTV'].isnull()].shape[0]
}

print("--- Quantos nulos em 'rate_of_interest' também são nulos em: ---")
for col, valor in intersecoes.items():
    print(f"{col}: {valor} linhas")

filtro_vazio_total = (
    df['rate_of_interest'].isnull() &
    df['property_value'].isnull() &
    df['LTV'].isnull()
)

# Isolamos essas linhas
df_conjunto_faltante = df[filtro_vazio_total]

# Calculamos a quantidade e a proporção de inadimplentes (Status 1)
total_linhas = df_conjunto_faltante.shape[0]
qtd_status_1 = df_conjunto_faltante['Status'].sum()
percentual = (qtd_status_1 / total_linhas) * 100

print(f"Total de linhas com as 3 colunas nulas: {total_linhas}")
print(f"Status 1 (Inadimplente): {qtd_status_1}")
print(f"Percentual de Inadimplência nesse grupo: {percentual:.2f}%")

df_clean = df[
    ((df['income'] > 0) | (df['income'].isnull())) &
    ((df['dtir1'] >= 0) | (df['dtir1'].isnull()))
].copy()

print(f"Base inicial de limpeza criada com {len(df_clean)} linhas.")

import numpy as np

df_clean['processo_interrompido'] = np.where(
    (df_clean['rate_of_interest'].isnull()) |
    (df_clean['property_value'].isnull()) |
    (df_clean['Interest_rate_spread'].isnull()) |
    (df_clean['LTV'].isnull()) |
    (df_clean['Upfront_charges'].isnull()),
    1, 0
)

print(df_clean['processo_interrompido'].value_counts())

cols_mediana_simples = ['term', 'age', 'submission_of_application']
for col in cols_mediana_simples:
    if df_clean[col].dtype == 'object':
        df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])
    else:
        df_clean[col] = df_clean[col].fillna(df_clean[col].median())


cols_moda = ['loan_limit', 'approv_in_adv', 'loan_purpose', 'Neg_ammortization']
for col in cols_moda:
    df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

renda_zero = df_clean[df_clean['income'] == 0]
print(f"Total de clientes com renda ZERO: {len(renda_zero)}")
print(f"Taxa de inadimplência (Status 1) neles: {renda_zero['Status'].mean():.2%}")


print(f"Valor médio do imóvel desses clientes: {renda_zero['property_value'].median()}")

import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor

# Mapeamento para o MICE
mapeamento_idade = {
    '25-34': 30, '35-44': 40, '45-54': 50, '55-64': 60,
    '65-74': 70, '>74': 80, '<25': 20
}
df_clean['age_num'] = df_clean['age'].map(mapeamento_idade)

# Seleção de colunas numéricas ---
colunas_para_mice = [
    'loan_amount', 'income', 'dtir1', 'Credit_Score',
    'processo_interrompido', 'term', 'age_num'
]

df_para_imputar = df_clean[colunas_para_mice].copy()

# Configuração do MICE com Random Forest Regressor
imputer = IterativeImputer(
    estimator=RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=42),
    max_iter=5,
    random_state=42
)

# Execução da imputação
dados_imputados = imputer.fit_transform(df_para_imputar)

# Criamos o DF final com os novos dados
df_final = pd.DataFrame(dados_imputados, columns=colunas_para_mice)

# Removendo a idade numérica auxiliar
df_final = df_final.drop(columns=['age_num'])

# Conferência final
print(df_final[['income', 'dtir1']].describe())

colunas_para_voltar = [
    'loan_limit', 'Gender', 'approv_in_adv', 'loan_type', 'loan_purpose',
    'Credit_Worthiness', 'business_or_commercial', 'Neg_ammortization',
    'interest_only', 'lump_sum_payment', 'construction_type', 'occupancy_type',
    'credit_type', 'co-applicant_credit_type', 'Region', 'submission_of_application','age','Status'
]

for col in colunas_para_voltar:
    if col in df_clean.columns:
        df_final[col] = df_clean[col].values

# 3. Verificação final
print("📊 Colunas agora presentes no df_final:")
print(df_final.columns.tolist())
print(f"\nValores nulos restantes:\n{df_final.isnull().sum().sum()}")

renda_zero = df_clean[df_clean['income'] == 0]
print(f"Total de clientes com renda ZERO: {len(renda_zero)}")
print(f"Taxa de inadimplência (Status 1) neles: {renda_zero['Status'].mean():.2%}")


print(f"Valor médio do imóvel desses clientes: {renda_zero['property_value'].median()}")

df_final.isnull().sum()

print("ANÁLISE DE VARIÂNCIA PÓS-MICE")
estatisticas = df_final[['income', 'dtir1']].describe()
print(estatisticas)

# Coeficiente de Variação
cv_income = (df_final['income'].std() / df_final['income'].mean()) * 100
cv_dtir = (df_final['dtir1'].std() / df_final['dtir1'].mean()) * 100

print(f"\nDispersão da Renda (CV): {cv_income:.2f}%")
print(f"Dispersão do DTI (CV): {cv_dtir:.2f}%")

plt.figure(figsize=(10, 8))
sns.heatmap(df_clean[['income', 'loan_amount', 'LTV', 'dtir1', 'Credit_Score', 'rate_of_interest', 'Status']].corr(),
            annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Matriz de Correlação das Variáveis Financeiras")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

#Arquivo responsável por validar Simetria, Outliers e Assimetria. Explicação detalhada GitHub


# Carregando o arquivo
df = df_clean

# Definindo as colunas numéricas para análise
cols_analise = ['dtir1', 'loan_amount', 'Credit_Score', 'LTV']

# Configurando a área de desenho
plt.figure(figsize=(16, 22))

for i, col in enumerate(cols_analise):
    # --- 1. Gráfico de Histograma (Padrões e Distribuição) ---
    plt.subplot(len(cols_analise), 2, 2*i + 1)

    # Criando o histograma
    sns.histplot(df[col].dropna(), kde=True, color='skyblue', bins=30)

    # Adiciona uma linha vertical para a Mediana
    mediana = df[col].median()
    plt.axvline(mediana, color='red', linestyle='--', label=f'Mediana: {mediana:.2f}')

    plt.title(f'Distribuição de {col}')
    plt.legend()

    # --- 2. Gráfico de Boxplot (Anomalias e Outliers) ---
    plt.subplot(len(cols_analise), 2, 2*i + 2)

    # Criando o boxplot
    sns.boxplot(x=df[col], color='lightgreen', fliersize=5)
    plt.title(f'Detecção de Outliers: {col}')
    plt.xlabel(f'Valores de {col}')

plt.tight_layout()
plt.show()

# Resumo estatístico rápido para conferência no console
print("--- Resumo das Medianas (Valores Centrais Reais) ---")
print(df[cols_analise].median())
#print(df.isnull().sum())

df = df_clean

# Ver a média de DTIR1 para quem pagou vs quem não pagou
print("Média de comprometimento de renda por Status:")
display(df.groupby('Status')['dtir1'].mean())


# Ver a mediana de LOAN
print("Mediana de loan de renda por Status:")
display(df.groupby('Status')['loan_amount'].median())


#Mediana LTV
print("Mediana de LTV de renda por Status:")
display(df.groupby('Status')['LTV'].median())

print("Media do empréstimo:", df['loan_amount'].mean())
print("Mediana do empréstimo:", df['loan_amount'].median())
print("Mediana do SCORE:", df['Credit_Score'].mean())

corr_status = df.corr(numeric_only=True)['Status'].sort_values(ascending=False)

plt.figure(figsize=(10, 5))
corr_status.drop('Status').plot(kind='bar')
plt.title("Correlação das Variáveis Numéricas com Status")
plt.ylabel("Coeficiente de Correlação")
plt.xlabel("Variáveis")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x='Status', y='dtir1')
plt.title("Distribuição do DTI por Status")
plt.xlabel("Status (0 = Adimplente, 1 = Inadimplente)")
plt.ylabel("DTI")
plt.show()

dti_mediana = df.groupby('Status')['dtir1'].median().reset_index()

plt.figure(figsize=(6, 4))
sns.barplot(data=dti_mediana, x='Status', y='dtir1')
plt.title("Mediana do DTI por Status")
plt.xlabel("Status")
plt.ylabel("DTI mediano")
plt.show()

print(dti_mediana)

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='Credit_Score', y='rate_of_interest', alpha=0.4)
plt.title("Credit Score vs Taxa de Juros")
plt.xlabel("Credit Score")
plt.ylabel("Taxa de Juros")
plt.show()

plt.figure(figsize=(4, 3))
sns.heatmap(df[['Credit_Score', 'rate_of_interest']].corr(), annot=True, cmap='coolwarm', fmt='.3f')
plt.title("Correlação: Score x Juros")
plt.show()

inad_regiao = df.groupby('Region')['Status'].mean().sort_values(ascending=False).reset_index()
inad_regiao['Status'] = inad_regiao['Status'] * 100

plt.figure(figsize=(8, 5))
sns.barplot(data=inad_regiao, x='Region', y='Status')
plt.title("Taxa de Inadimplência por Região")
plt.xlabel("Região")
plt.ylabel("Inadimplência (%)")
plt.show()

print(inad_regiao)

imovel_regiao = df.groupby('Region')['property_value'].median().sort_values().reset_index()

plt.figure(figsize=(8, 5))
sns.barplot(data=imovel_regiao, x='Region', y='property_value')
plt.title("Valor Mediano do Imóvel por Região")
plt.xlabel("Região")
plt.ylabel("Valor Mediano do Imóvel")
plt.show()

print(imovel_regiao)

inad_idade = df.groupby('age', observed=False)['Status'].mean().reset_index()
inad_idade['Status'] = inad_idade['Status'] * 100

ordem_idade = ['<25', '25-34', '35-44', '45-54', '55-64', '65-74', '>74']

plt.figure(figsize=(8,5))
sns.barplot(data=inad_idade, x='age', y='Status', order=ordem_idade)
plt.title("Taxa de Inadimplência por Faixa Etária")
plt.xlabel("Faixa Etária")
plt.ylabel("Inadimplência (%)")
plt.xticks(rotation=30)
plt.show()

print(inad_idade)

renda_idade = df.groupby('age', observed=False)['income'].median().reset_index()

plt.figure(figsize=(8,5))
sns.barplot(data=renda_idade, x='age', y='income', order=ordem_idade)
plt.title("Renda Mediana por Faixa Etária")
plt.xlabel("Faixa Etária")
plt.ylabel("Renda Mediana")
plt.xticks(rotation=30)
plt.show()

print(renda_idade)

inad_interest = df.groupby('interest_only')['Status'].mean().reset_index()
inad_interest['Status'] = inad_interest['Status'] * 100

plt.figure(figsize=(7, 5))
sns.barplot(data=inad_interest, x='interest_only', y='Status')
plt.title("Taxa de Inadimplência por Modalidade Interest-Only")
plt.xlabel("Interest Only")
plt.ylabel("Inadimplência (%)")
plt.show()

print(inad_interest)

score_genero = df.groupby('Gender')['Credit_Score'].mean().reset_index()

plt.figure(figsize=(7, 5))
sns.barplot(data=score_genero, x='Gender', y='Credit_Score')
plt.title("Credit Score Médio por Gênero")
plt.xlabel("Gênero")
plt.ylabel("Score Médio")
plt.show()

print(score_genero)

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x='Gender', y='Credit_Score')
plt.title("Distribuição do Credit Score por Gênero")
plt.xlabel("Gênero")
plt.ylabel("Credit Score")
plt.show()

ltv_ocup = df.groupby('occupancy_type')['LTV'].mean().reset_index().sort_values(by='LTV', ascending=False)

plt.figure(figsize=(8, 5))
sns.barplot(data=ltv_ocup, x='occupancy_type', y='LTV')
plt.title("LTV Médio por Tipo de Ocupação")
plt.xlabel("Tipo de Ocupação")
plt.ylabel("LTV Médio")
plt.xticks(rotation=20)
plt.show()

print(ltv_ocup)

plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x='occupancy_type', y='LTV')
plt.title("Distribuição do LTV por Tipo de Ocupação")
plt.xlabel("Tipo de Ocupação")
plt.ylabel("LTV")
plt.xticks(rotation=20)
plt.show()

# =============================================================================
# ANÁLISE DE CORRELAÇÃO
# =============================================================================

df = df_clean

# ─── Configurações visuais ────────────────────────────────────────────────────
C0 = "#2ecc71"   # Adimplente
C1 = "#e74c3c"   # Inadimplente
BG = "#f8f9fa"
ACCENT = "#2c3e50"
OUT = "graficos_correlacao/"

plt.rcParams.update({
    'font.family': 'DejaVu Sans',
    'axes.facecolor': BG,
    'figure.facecolor': 'white',
    'axes.spines.top': False,
    'axes.spines.right': False,
})

os.makedirs(OUT, exist_ok=True)

# Re-import scipy.stats to ensure 'stats' refers to the module, not the DataFrame
from scipy import stats

# ─── Correlações de Pearson ───────────────────────────────────────────────────
print("=== CORRELAÇÕES DE PEARSON ===")
pairs = [
    ('LTV', 'Status'),
    ('dtir1', 'Status'),
    ('Credit_Score', 'rate_of_interest'),
    ('loan_amount', 'Upfront_charges'),
    ('Credit_Score', 'Status'),
    ('rate_of_interest', 'Status'),
]
for a, b in pairs:
    d = df[[a, b]].dropna()
    r, p = stats.pearsonr(d[a], d[b])
    print(f"  {a} x {b}: r={r:.4f}, p={p:.2e}, n={len(d)}")

fig, ax = plt.subplots(figsize=(12, 9))
fig.suptitle("Mapa de Calor — Correlação de Pearson entre Variáveis Numéricas",
             fontsize=15, fontweight='bold', color=ACCENT)

num_cols = ['loan_amount','rate_of_interest','Upfront_charges','property_value',
            'income','Credit_Score','LTV','dtir1','term','Status']
corr = df[num_cols].corr(method='pearson')
labels = {
    'loan_amount': 'Valor Empréstimo', 'rate_of_interest': 'Taxa de Juros',
    'Upfront_charges': 'Taxas Iniciais', 'property_value': 'Valor Imóvel',
    'income': 'Renda', 'Credit_Score': 'Credit Score',
    'LTV': 'LTV', 'dtir1': 'DTI', 'term': 'Prazo', 'Status': 'Status (Default)'
}
corr.rename(index=labels, columns=labels, inplace=True)
sns.heatmap(corr, ax=ax, annot=True, fmt='.2f', cmap='RdYlGn',
            center=0, vmin=-1, vmax=1,
            linewidths=0.5, linecolor='white',
            annot_kws={'size': 10, 'weight': 'bold'})
plt.xticks(rotation=30, ha='right'); plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig(OUT + '12_heatmap_correlacao.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 1. LTV vs Status ─────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("LTV vs. Status de Inadimplência", fontsize=16, fontweight='bold', color=ACCENT)

d = df[df['LTV'] < 200].copy()
d['Status_label'] = d['Status'].map({0: 'Adimplente', 1: 'Inadimplente'})

bp = axes[0].boxplot(
    [d[d['Status']==0]['LTV'].dropna(), d[d['Status']==1]['LTV'].dropna()],
    labels=['Adimplente', 'Inadimplente'],
    patch_artist=True, medianprops=dict(color='black', linewidth=2)
)
bp['boxes'][0].set_facecolor(C0); bp['boxes'][0].set_alpha(0.8)
bp['boxes'][1].set_facecolor(C1); bp['boxes'][1].set_alpha(0.8)
axes[0].set_title('Distribuição do LTV por Status')
axes[0].set_ylabel('LTV (%)')

means = d.groupby('Status_label')['LTV'].mean()
bars = axes[1].bar(means.index, means.values, color=[C0, C1], alpha=0.85, width=0.5)
for bar, val in zip(bars, means.values):
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                 f'{val:.1f}%', ha='center', va='bottom', fontweight='bold')
axes[1].set_title('LTV Médio por Status')
axes[1].set_ylabel('LTV Médio (%)')
plt.tight_layout()
plt.savefig(OUT + '01_ltv_vs_status.png', dpi=150, bbox_inches='tight')

plt.show()

# ─── 2. DTI vs Status ─────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("DTI vs. Status de Inadimplência", fontsize=16, fontweight='bold', color=ACCENT)

d = df[['dtir1', 'Status']].dropna()
d['Status_label'] = d['Status'].map({0: 'Adimplente', 1: 'Inadimplente'})

bp = axes[0].boxplot(
    [d[d['Status']==0]['dtir1'], d[d['Status']==1]['dtir1']],
    labels=['Adimplente', 'Inadimplente'],
    patch_artist=True, medianprops=dict(color='black', linewidth=2)
)
bp['boxes'][0].set_facecolor(C0); bp['boxes'][0].set_alpha(0.8)
bp['boxes'][1].set_facecolor(C1); bp['boxes'][1].set_alpha(0.8)
axes[0].set_title('Distribuição do DTI por Status')
axes[0].set_ylabel('DTI (%)')

d['dti_bucket'] = pd.cut(d['dtir1'], bins=[0,20,30,40,50,62],
                          labels=['<20','20-30','30-40','40-50','>50'])
dr = d.groupby('dti_bucket', observed=True)['Status'].mean() * 100
axes[1].bar(dr.index.astype(str), dr.values, color='#e67e22', alpha=0.85, width=0.6)
for i, val in enumerate(dr.values):
    axes[1].text(i, val + 0.3, f'{val:.1f}%', ha='center', va='bottom', fontweight='bold')
axes[1].set_title('Taxa de Inadimplência por Faixa de DTI')
axes[1].set_ylabel('Taxa de Inadimplência (%)')
axes[1].set_xlabel('Faixa de DTI (%)')
plt.tight_layout()
plt.savefig(OUT + '02_dti_vs_status.png', dpi=150, bbox_inches='tight')

plt.show()

# ─── 3. Credit Score vs Taxa de Juros ─────────────────────────────────────────
import scipy.stats as stats # Re-import stats to ensure it refers to the scipy.stats module

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("Credit Score vs. Taxa de Juros", fontsize=16, fontweight='bold', color=ACCENT)

d = df[['Credit_Score', 'rate_of_interest']].dropna()
sample = d.sample(min(5000, len(d)), random_state=42)
axes[0].scatter(sample['Credit_Score'], sample['rate_of_interest'],
                alpha=0.15, color='#3498db', s=10)
m, b, r, p, se = stats.linregress(d['Credit_Score'], d['rate_of_interest'])
x_line = np.linspace(d['Credit_Score'].min(), d['Credit_Score'].max(), 200)
axes[0].plot(x_line, m*x_line+b, color='#e74c3c', linewidth=2,
             label=f'r = {r:.3f}\np = {p:.3f}')
axes[0].set_xlabel('Credit Score'); axes[0].set_ylabel('Taxa de Juros (%)')
axes[0].set_title('Dispersão: Score vs. Juros'); axes[0].legend()

d['score_bucket'] = pd.cut(d['Credit_Score'], bins=[400,550,650,700,750,900],
                             labels=['400-550','550-650','650-700','700-750','750+'])
mean_rate = d.groupby('score_bucket', observed=True)['rate_of_interest'].mean()
axes[1].bar(mean_rate.index.astype(str), mean_rate.values, color='#9b59b6', alpha=0.85, width=0.6)
for i, val in enumerate(mean_rate.values):
    axes[1].text(i, val + 0.02, f'{val:.2f}%', ha='center', va='bottom', fontweight='bold', fontsize=9)
axes[1].set_title('Juros Médio por Faixa de Score')
axes[1].set_ylabel('Taxa de Juros Média (%)')
axes[1].set_xlabel('Faixa de Credit Score')
plt.tight_layout()
plt.savefig(OUT + '03_creditscore_vs_interest.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 4. Valor do Empréstimo vs. Taxas Iniciais ────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("Valor do Empréstimo vs. Taxas Iniciais", fontsize=16, fontweight='bold', color=ACCENT)

d = df[['loan_amount', 'Upfront_charges']].dropna()
d = d[d['loan_amount'] < d['loan_amount'].quantile(0.99)]
d = d[d['Upfront_charges'] < d['Upfront_charges'].quantile(0.99)]
sample = d.sample(min(5000, len(d)), random_state=42)
axes[0].scatter(sample['loan_amount'], sample['Upfront_charges'], alpha=0.15, color='#1abc9c', s=10)
m, b, r, p, se = stats.linregress(d['loan_amount'], d['Upfront_charges'])
x_line = np.linspace(d['loan_amount'].min(), d['loan_amount'].max(), 200)
axes[0].plot(x_line, m*x_line+b, color='#e74c3c', linewidth=2, label=f'r = {r:.3f}')
axes[0].set_xlabel('Valor do Empréstimo (USD)'); axes[0].set_ylabel('Taxas Iniciais (USD)')
axes[0].set_title('Dispersão: Empréstimo vs. Taxas'); axes[0].legend()

d['charges_pct'] = (d['Upfront_charges'] / d['loan_amount']) * 100
d['loan_bucket'] = pd.cut(d['loan_amount'], bins=[0,100000,200000,300000,500000,10000000],
                            labels=['<100k','100-200k','200-300k','300-500k','>500k'])
mean_pct = d.groupby('loan_bucket', observed=True)['charges_pct'].mean()
axes[1].bar(mean_pct.index.astype(str), mean_pct.values, color='#1abc9c', alpha=0.85, width=0.6)
for i, val in enumerate(mean_pct.values):
    axes[1].text(i, val + 0.02, f'{val:.2f}%', ha='center', va='bottom', fontweight='bold', fontsize=9)
axes[1].set_title('Taxa Inicial Média (% do Empréstimo)')
axes[1].set_ylabel('Taxas Iniciais / Empréstimo (%)')
axes[1].set_xlabel('Faixa do Empréstimo')
plt.tight_layout()
plt.savefig(OUT + '04_loanamount_vs_upfront.png', dpi=150, bbox_inches='tight')
plt.show()

# --- 5. Região vs. Valor do Imóvel
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle("Análise Regional: Valor do Imóvel", fontsize=16, fontweight='bold', color='#2c3e50')

d = df_clean[['Region','property_value']]
regions = sorted(d['Region'].unique())
colors_r = ['#3498db','#e67e22','#9b59b6','#2ecc71']

# --- Gráfico 1: Boxplot com Limite de Eixo (Zoom) ---
data_r = [d[d['Region']==r]['property_value'].values for r in regions]
bp = axes[0].boxplot(data_r, labels=regions, patch_artist=True, showfliers=True,
                     medianprops=dict(color='black', linewidth=2),
                     flierprops=dict(marker='o', markersize=3, alpha=0.2)) # Outliers menores e transparentes

for patch, color in zip(bp['boxes'], colors_r):
    patch.set_facecolor(color)
    patch.set_alpha(0.7)

axes[0].set_title('Distribuição (Foco até $2M)')
axes[0].set_ylabel('Valor do Imóvel (USD)')
axes[0].set_ylim(0, 2000000)
axes[0].yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x*1e-6:.1f}M'))

# --- Gráfico 2: Barras Mediana ---
medians_r = d.groupby('Region')['property_value'].median().reindex(regions)
bars = axes[1].bar(medians_r.index, medians_r.values / 1000, color=colors_r, alpha=0.85, width=0.5)

for bar, val in zip(bars, medians_r.values / 1000):
    axes[1].text(bar.get_x()+bar.get_width()/2, bar.get_height()+5,
                 f'${val:.0f}k', ha='center', va='bottom', fontweight='bold', fontsize=11)

axes[1].set_title('Valor Mediano por Região')
axes[1].set_ylabel('Valor Mediano (USD mil)')
axes[1].set_ylim(0, medians_r.max()/1000 + 100)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# ─── 6. Região vs. Taxa de Inadimplência ──────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("Região vs. Taxa de Inadimplência", fontsize=16, fontweight='bold', color=ACCENT)

d = df[['Region','Status']].dropna()
dr_reg = d.groupby('Region')['Status'].mean() * 100
dr_reg = dr_reg.sort_values(ascending=False)
bars = axes[0].bar(dr_reg.index, dr_reg.values, color=colors_r[:len(dr_reg)], alpha=0.85, width=0.6)
for bar, val in zip(bars, dr_reg.values):
    axes[0].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.2,
                 f'{val:.1f}%', ha='center', va='bottom', fontweight='bold')
axes[0].axhline(df['Status'].mean()*100, color='black', linestyle='--', linewidth=1.5,
                label=f'Média geral: {df["Status"].mean()*100:.1f}%')
axes[0].set_title('Taxa de Inadimplência por Região')
axes[0].set_ylabel('Taxa de Inadimplência (%)'); axes[0].legend()

count_reg = d.groupby(['Region','Status']).size().unstack()
count_reg.columns = ['Adimplentes','Inadimplentes']
count_reg.plot(kind='bar', ax=axes[1], color=[C0, C1], alpha=0.85, width=0.7)
axes[1].set_title('Volume de Adimplentes vs Inadimplentes')
axes[1].set_xlabel('Região'); axes[1].set_ylabel('Número de Empréstimos')
axes[1].tick_params(axis='x', rotation=30); axes[1].legend()
plt.tight_layout()
plt.savefig(OUT + '06_region_vs_status.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 7. Tipo de Ocupação vs. LTV ──────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("Tipo de Ocupação vs. LTV", fontsize=16, fontweight='bold', color=ACCENT)

d = df[['occupancy_type','LTV']].dropna()
d = d[d['LTV'] < 200]
occ_labels = {'pr': 'Residência Principal', 'ir': 'Investimento', 'sr': 'Segunda Residência'}
d['occ_label'] = d['occupancy_type'].map(occ_labels)
occ_order = ['Residência Principal', 'Investimento', 'Segunda Residência']
colors_o = ['#3498db','#e74c3c','#f39c12']
data_occ = [d[d['occ_label']==o]['LTV'].values for o in occ_order]
bp = axes[0].boxplot(data_occ, labels=occ_order, patch_artist=True,
                     medianprops=dict(color='black', linewidth=2))
for patch, color in zip(bp['boxes'], colors_o): patch.set_facecolor(color); patch.set_alpha(0.8)
axes[0].set_title('LTV por Tipo de Ocupação'); axes[0].set_ylabel('LTV (%)')
axes[0].tick_params(axis='x', rotation=15)
means_o = d.groupby('occ_label')['LTV'].mean().reindex(occ_order)
bars = axes[1].bar(means_o.index, means_o.values, color=colors_o, alpha=0.85, width=0.5)
for bar, val in zip(bars, means_o.values):
    axes[1].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.3,
                 f'{val:.1f}%', ha='center', va='bottom', fontweight='bold')
axes[1].set_title('LTV Médio por Tipo de Ocupação'); axes[1].set_ylabel('LTV Médio (%)')
axes[1].tick_params(axis='x', rotation=15)
plt.tight_layout()
plt.savefig(OUT + '07_occupancy_vs_ltv.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 8. Faixa Etária vs. Renda ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("Faixa Etária vs. Renda", fontsize=16, fontweight='bold', color=ACCENT)

age_order = ['<25','25-34','35-44','45-54','55-64','65-74','>74']
d = df[['age','income']].dropna()
d = d[d['income'] < d['income'].quantile(0.99)]
d_filt = d[d['age'].isin(age_order)]
colors_age = plt.cm.viridis(np.linspace(0.2, 0.85, len(age_order)))
data_age = [d_filt[d_filt['age']==a]['income'].values for a in age_order]
bp = axes[0].boxplot(data_age, labels=age_order, patch_artist=True,
                     medianprops=dict(color='black', linewidth=2))
for patch, color in zip(bp['boxes'], colors_age): patch.set_facecolor(color); patch.set_alpha(0.8)
axes[0].set_title('Distribuição da Renda por Faixa Etária'); axes[0].set_ylabel('Renda Mensal (USD)')
means_age = d_filt.groupby('age')['income'].median().reindex(age_order)
axes[1].plot(age_order, means_age.values, marker='o', color='#e74c3c', linewidth=2.5, markersize=8)
axes[1].fill_between(range(len(age_order)), means_age.values, alpha=0.15, color='#e74c3c')
axes[1].set_xticks(range(len(age_order))); axes[1].set_xticklabels(age_order)
axes[1].set_title('Renda Mediana por Faixa Etária'); axes[1].set_ylabel('Renda Mediana (USD)')
plt.tight_layout()
plt.savefig(OUT + '08_age_vs_income.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 9. Gênero vs. Credit Score ───────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("Gênero vs. Credit Score", fontsize=16, fontweight='bold', color=ACCENT)

d = df[df['Gender'].isin(['Male','Female','Joint'])][['Gender','Credit_Score']]
gender_colors = {'Male': '#3498db', 'Female': '#e91e8c', 'Joint': '#9b59b6'}
data_g = [d[d['Gender']==g]['Credit_Score'].values for g in ['Male','Female','Joint']]
bp = axes[0].boxplot(data_g, labels=['Masculino','Feminino','Conjunto'],
                     patch_artist=True, medianprops=dict(color='black', linewidth=2))
for patch, c in zip(bp['boxes'], gender_colors.values()): patch.set_facecolor(c); patch.set_alpha(0.8)
axes[0].set_title('Distribuição do Score por Gênero'); axes[0].set_ylabel('Credit Score')
means_g = d.replace({'Gender': {'Male':'Masculino','Female':'Feminino','Joint':'Conjunto'}}).groupby('Gender')['Credit_Score'].mean()
order_g = ['Masculino','Feminino','Conjunto']
means_g = means_g.reindex(order_g)
bars = axes[1].bar(means_g.index, means_g.values,
                   color=['#3498db','#e91e8c','#9b59b6'], alpha=0.85, width=0.5)
for bar, val in zip(bars, means_g.values):
    axes[1].text(bar.get_x()+bar.get_width()/2, bar.get_height()+1,
                 f'{val:.0f}', ha='center', va='bottom', fontweight='bold')
axes[1].set_title('Score Médio por Gênero'); axes[1].set_ylabel('Credit Score Médio')
axes[1].set_ylim(600, 720)
plt.tight_layout()
plt.savefig(OUT + '09_gender_vs_creditscore.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 10. Faixa Etária vs. Inadimplência ───────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("Faixa Etária vs. Inadimplência", fontsize=16, fontweight='bold', color=ACCENT)

d = df[df['age'].isin(age_order)][['age','Status']]
dr_age = d.groupby('age')['Status'].mean() * 100
dr_age = dr_age.reindex(age_order)
bars = axes[0].bar(age_order, dr_age.values,
                   color=plt.cm.RdYlGn_r(np.linspace(0.1, 0.9, len(age_order))), alpha=0.85, width=0.6)
for bar, val in zip(bars, dr_age.values):
    axes[0].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.3,
                 f'{val:.1f}%', ha='center', va='bottom', fontweight='bold', fontsize=9)
axes[0].axhline(df['Status'].mean()*100, color='black', linestyle='--', linewidth=1.5,
                label=f'Média: {df["Status"].mean()*100:.1f}%')
axes[0].set_title('Taxa de Inadimplência por Faixa Etária')
axes[0].set_ylabel('Taxa de Inadimplência (%)'); axes[0].set_xlabel('Faixa Etária')
axes[0].legend()
count_age_d = d[d['Status']==1].groupby('age').size().reindex(age_order)
count_age_a = d[d['Status']==0].groupby('age').size().reindex(age_order)
stacked = pd.DataFrame({'Adimplentes': count_age_a, 'Inadimplentes': count_age_d})
stacked.plot(kind='bar', ax=axes[1], color=[C0, C1], alpha=0.85, width=0.7)
axes[1].set_title('Volume por Faixa Etária e Status')
axes[1].set_xlabel('Faixa Etária'); axes[1].set_ylabel('Número de Empréstimos')
axes[1].tick_params(axis='x', rotation=30); axes[1].legend()
plt.tight_layout()
plt.savefig(OUT + '10_age_vs_status.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 11. Modalidade Interest-Only vs. Inadimplência ───────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle("Modalidade Interest-Only vs. Inadimplência", fontsize=16, fontweight='bold', color=ACCENT)

d = df[['interest_only','Status']].copy()
io_labels = {'not_int': 'Amortização Normal', 'int_only': 'Apenas Juros'}
d['io_label'] = d['interest_only'].map(io_labels)
dr_io = d.groupby('io_label')['Status'].mean() * 100
bars = axes[0].bar(dr_io.index, dr_io.values, color=['#2ecc71','#e74c3c'], alpha=0.85, width=0.5)
for bar, val in zip(bars, dr_io.values):
    axes[0].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.2,
                 f'{val:.1f}%', ha='center', va='bottom', fontweight='bold', fontsize=12)
axes[0].set_title('Taxa de Inadimplência por Modalidade'); axes[0].set_ylabel('Taxa de Inadimplência (%)')
count_io = d.groupby(['io_label','Status']).size().unstack()
count_io.columns = ['Adimplente','Inadimplente']
count_io.plot(kind='bar', ax=axes[1], color=[C0, C1], alpha=0.85, width=0.5)
axes[1].set_title('Volume por Modalidade e Status')
axes[1].set_xlabel('Modalidade de Pagamento'); axes[1].set_ylabel('Número de Contratos')
axes[1].tick_params(axis='x', rotation=15); axes[1].legend()
plt.tight_layout()
plt.savefig(OUT + '11_interestonly_vs_status.png', dpi=150, bbox_inches='tight')
plt.show()

X = df_final.drop('Status', axis=1)
y = df_final['Status']

# Transforma todas as colunas de texto em números (0 e 1)
X = pd.get_dummies(X)

print(f"Total de {X.shape[1]} colunas.")

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Treino: {X_train.shape[0]} amostras")
print(f"Teste: {X_test.shape[0]} amostras")

X.head()

X.info()

# 1. Inicializar o modelo
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

# 2. Treinar o modelo
rf_model.fit(X_train, y_train)

# 3. Fazer previsões
y_pred = rf_model.predict(X_test)

print("\n--- Relatório de Classificação ---")
print(classification_report(y_test, y_pred))

importances = rf_model.feature_importances_
indices = np.argsort(importances)[-10:]

plt.figure(figsize=(10, 6))
plt.title('10 Variáveis Mais Importantes para Prever o Status')
plt.barh(range(len(indices)), importances[indices], color='b', align='center')
plt.yticks(range(len(indices)), [X.columns[i] for i in indices])
plt.xlabel('Importância Relativa')
plt.show()

colunas_para_remover = ['Status', 'credit_type']


X = df_final.drop(columns=colunas_para_remover)
y = df_final['Status']

X_encoded = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)

# Treinando o Random Forest
from sklearn.ensemble import RandomForestClassifier
rf_realista = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
rf_realista.fit(X_train, y_train)

from sklearn.metrics import classification_report
y_pred = rf_realista.predict(X_test)

print("\n--- Relatório SEM 'credit_type' ---")
print(classification_report(y_test, y_pred))

colunas_para_remover = ['Status', 'processo_interrompido']

X_puro = df_final.drop(columns=colunas_para_remover)
y = df_final['Status']

# Transformando categorias em números
X_encoded_puro = pd.get_dummies(X_puro, drop_first=True)

# Divisão Treino/Teste
from sklearn.model_selection import train_test_split
X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(
    X_encoded_puro, y, test_size=0.2, random_state=42, stratify=y
)

# Treinando o modelo
from sklearn.ensemble import RandomForestClassifier
rf_puro = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
rf_puro.fit(X_train_p, y_train_p)

# Avaliando
from sklearn.metrics import classification_report
y_pred_p = rf_puro.predict(X_test_p)


print(classification_report(y_test_p, y_pred_p))


import matplotlib.pyplot as plt
importencias = pd.Series(rf_puro.feature_importances_, index=X_encoded_puro.columns)
importencias.nlargest(10).plot(kind='barh')
plt.title("10 Variáveis mais importantes")
plt.show()

colunas_para_remover = ['Status', 'processo_interrompido','credit_type']

X_puro = df_final.drop(columns=colunas_para_remover)
y = df_final['Status']

X_encoded_puro = pd.get_dummies(X_puro, drop_first=True)

# Divisão Treino/Teste
from sklearn.model_selection import train_test_split
X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(
    X_encoded_puro, y, test_size=0.2, random_state=42, stratify=y
)

# Treinando o modelo
from sklearn.ensemble import RandomForestClassifier
rf_puro = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
rf_puro.fit(X_train_p, y_train_p)

# Avaliando
from sklearn.metrics import classification_report
y_pred_p = rf_puro.predict(X_test_p)

print(classification_report(y_test_p, y_pred_p))

# Nova Importância de Variáveis
import matplotlib.pyplot as plt
importencias = pd.Series(rf_puro.feature_importances_, index=X_encoded_puro.columns)
importencias.nlargest(10).plot(kind='barh')
plt.title("'10 Variáveis Mais Importantes")
plt.show()

print(df_final.columns.tolist())

from sklearn.model_selection import GridSearchCV

param_grid = {

    'n_estimators': [100, 200, 500],


    'max_depth': [10, 20, 30, None],


    'min_samples_split': [2, 5, 10],


    'min_samples_leaf': [1, 2, 4],


    'criterion': ['gini', 'entropy'],


    'class_weight': ['balanced', 'balanced_subsample', None]
}

colunas_para_remover = ['Status', 'processo_interrompido']

X = df_final.drop(columns=colunas_para_remover)
y = df_final['Status']


X_encoded = pd.get_dummies(X, drop_first=True)


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)

from sklearn.model_selection import RandomizedSearchCV

# Configuração da busca
rf_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=42, n_jobs=-1),
    param_distributions=param_grid,
    n_iter=20,
    cv=3,
    scoring='f1',
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# Execução
rf_search.fit(X_train, y_train)

print(f"Melhores Parâmetros: {rf_search.best_params_}")

# 1. Garantindo a retirada das colunas
colunas_para_remover = ['Status', 'processo_interrompido']
X = df_final.drop(columns=colunas_para_remover)
y = df_final['Status']

# 2. Transformação em dummies
X_encoded = pd.get_dummies(X, drop_first=True)

# 3. Split de Treino e Teste
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)


modelo_final = RandomForestClassifier(
    n_estimators=200,
    min_samples_split=10,
    min_samples_leaf=1,
    max_depth=30,
    criterion='gini',
    class_weight='balanced_subsample',
    random_state=42,
    n_jobs=-1
)

modelo_final.fit(X_train, y_train)

# 5. Avaliação Final
y_pred_final = modelo_final.predict(X_test)
print("\n--- RELATÓRIO FINAL (PARÂMETRO F1) ---")
print(classification_report(y_test, y_pred_final))

import matplotlib.pyplot as plt
import pandas as pd

# 1. Extraindo as importâncias e associando aos nomes das colunas
importancias = modelo_final.feature_importances_
nomes_colunas = X_train.columns

# 2. Criando um DataFrame para facilitar a visualização
df_importancia = pd.DataFrame({'Variável': nomes_colunas, 'Importância (%)': importancias * 100})
df_importancia = df_importancia.sort_values(by='Importância (%)', ascending=True)

# 3. Plotando o gráfico de barras horizontais
plt.figure(figsize=(10, 8))
plt.barh(df_importancia['Variável'], df_importancia['Importância (%)'], color='skyblue')
plt.xlabel('Importância (%)')
plt.title('O que mais importa para a decisão do modelo')
plt.grid(axis='x', linestyle='--', alpha=0.7)

# Adicionando os valores percentuais nas barras
for i, v in enumerate(df_importancia['Importância (%)']):
    plt.text(v + 0.5, i, f"{v:.2f}%", va='center', fontsize=10)

plt.show()


print("\n--- PORCENTAGEM DE IMPORTÂNCIA (TOP 10) ---")
print(df_importancia.sort_values(by='Importância (%)', ascending=False).head(10).to_string(index=False))



colunas_para_remover = ['Status', 'processo_interrompido']


X = df_final.drop(columns=colunas_para_remover)
y = df_final['Status']


X_encoded = pd.get_dummies(X, drop_first=True)


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)


from sklearn.model_selection import RandomizedSearchCV

# Configuração da busca
rf_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=42, n_jobs=-1),
    param_distributions=param_grid,
    n_iter=20,
    cv=3,
    scoring='recall',
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# Execução
rf_search.fit(X_train, y_train)

print(f"Melhores Parâmetros: {rf_search.best_params_}")

# 1. Garantindo a retirada das colunas
colunas_para_remover = ['Status', 'processo_interrompido']
X = df_final.drop(columns=colunas_para_remover)
y = df_final['Status']

# 2. Transformação em dummies
X_encoded = pd.get_dummies(X, drop_first=True)

# 3. Split de Treino e Teste
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)

#
modelo_final = RandomForestClassifier(
    n_estimators=200,
    min_samples_split=5,
    min_samples_leaf=1,
    max_depth=10,
    criterion='gini',
    class_weight='balanced_subsample',
    random_state=42,
    n_jobs=-1
)

modelo_final.fit(X_train, y_train)

# 5. Avaliação Final
y_pred_final = modelo_final.predict(X_test)
print("\n--- RELATÓRIO FINAL (PARÂMETRO Recall) ---")
print(classification_report(y_test, y_pred_final))

colunas_para_remover = ['Status', 'processo_interrompido']


X = df_final.drop(columns=colunas_para_remover)
y = df_final['Status']


X_encoded = pd.get_dummies(X, drop_first=True)


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)


from sklearn.model_selection import RandomizedSearchCV

# Configuração da busca
rf_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=42, n_jobs=-1),
    param_distributions=param_grid,
    n_iter=20,
    cv=3,
    scoring='precision',
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# Execução
rf_search.fit(X_train, y_train)

print(f"Melhores Parâmetros: {rf_search.best_params_}")

colunas_para_remover = ['Status', 'processo_interrompido']
X = df_final.drop(columns=colunas_para_remover)
y = df_final['Status']

# 2. Transformação em dummies
X_encoded = pd.get_dummies(X, drop_first=True)

# 3. Split de Treino e Teste
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)

#
modelo_final = RandomForestClassifier(
    n_estimators=200,
    min_samples_split=10,
    min_samples_leaf=2,
    max_depth=10,
    criterion='gini',
    class_weight=None,
    random_state=42,
    n_jobs=-1
)

modelo_final.fit(X_train, y_train)

# 5. Avaliação Final
y_pred_final = modelo_final.predict(X_test)
print("\n--- RELATÓRIO FINAL (PARÂMETRO precisao) ---")
print(classification_report(y_test, y_pred_final))

import seaborn as sns
import matplotlib.pyplot as plt


suspicious_cols = ['income', 'dtir1']

plt.figure(figsize=(12, 5))
for i, col in enumerate(suspicious_cols):
    plt.subplot(1, 2, i+1)
    sns.kdeplot(data=df_clean, x=col, hue='Status', fill=True)
    plt.title(f'Distribuição de {col} por Status')

plt.tight_layout()
plt.show()